# Generated by Django 4.1.5 on 2023-02-07 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(default=1, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(default=1, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(default=1, max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brands')),
            ],
            options={
                'verbose_name_plural': 'Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('黑色', '黑色'), ('白色', '白色'), ('金色', '金色'), ('银色', '银色'), ('其他', '其他')], default='黑色', max_length=4)),
                ('useage', models.CharField(choices=[('全新未拆封', '全新未拆封'), ('拆封九新', '拆封九新'), ('经常使用', '经常使用'), ('日常使用', '日常使用')], default='全新未拆封', max_length=10)),
                ('condition', models.CharField(choices=[('全新', '全新'), ('有包装/无磨损', '有包装无磨损'), ('有包装/轻微磨损', '有包装轻微磨损'), ('无包装/轻微磨损', '无包装轻微磨损'), ('无包装/磨损较严重', '无包装磨损较严重')], default='全新', max_length=20)),
                ('age', models.CharField(choices=[('三个月内', '三个月内'), ('六个月内', '六个月内'), ('一年以内', '一年以内'), ('两年以内', '两年以内'), ('两年以上', '两年以上')], default='三个月内', max_length=10)),
                ('warranty', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.brands')),
                ('model_number', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.modelnumbers')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='MidCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(default=1, max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.categories')),
            ],
            options={
                'verbose_name_plural': 'Mid Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='brands',
            name='mid_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.midcategories'),
        ),
    ]
